name: bymn_barcode_example
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  riverpod: ^2.5.1
  hooks_riverpod: ^2.5.1
  dio: ^5.5.0+1
  logger: ^2.4.0
  go_router: ^14.2.3
  google_fonts: ^6.2.1
  pretty_dio_logger: ^1.4.0
  flutter_native_splash: ^2.4.0
  skeletons: ^0.0.3
  flutter_form_builder: ^9.2.1
  flutter_hooks: ^0.20.5
  modal_bottom_sheet:
    git:
      url: https://github.com/followthemoney1/modal_bottom_sheet.git
      ref: main
      path: modal_bottom_sheet
  font_awesome_flutter: ^10.7.0
  flutter_barcode_scanner: ^2.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.9
  freezed: ^2.5.2

flutter:
  uses-material-design: true
  assets:
     - assets/


flutter_native_splash:
  color: "#424242"
  image: assets/splash.png
  fullscreen: true
  web: false
  android_12:
    image: assets/splash_android_12.png
